name: Update Weekly Selection

# Run every Monday at 07:00 UTC, plus allow manual trigger
on:
  schedule:
    - cron: "0 7 * * 1"
  workflow_dispatch:

jobs:
  update_playlist:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Install Poetry
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      # 4. Install dependencies
      - name: Install dependencies
        run: poetry install

      # 5. Run the script
      - name: Run weekly selection
        run: poetry run python -m atzar.main
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
          SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}
          WEEKLY_SELECTION_PLAYLIST_ID: ${{ secrets.WEEKLY_SELECTION_PLAYLIST_ID }}
          STARRED_PLAYLIST_ID: ${{ secrets.STARRED_PLAYLIST_ID }}
